package com.example.abonekaptanmobile.data.remote.model

/**
 * Data class representing a single item in the response from a text generation API call.
 *
 * @property generated_text The text generated by the model.
 */
data class TextGenerationResponseItem(
    val generated_text: String
)
